spring.application.name=API Teste
## Porta de acesso ao Projeto
server.port = 8080
## Configura URL do banco
## � importante que o MySQL esteja preparado com o banco antes de executar esse programa
spring.datasource.url=jdbc:mysql://localhost:3306/ CRUD
## Usu�rio de acesso
spring.datasource.username=root
## Senha do banco
spring.datasource.password=9532
## Configura atualiza��es do banco -> Caso esteja como valor "update" a sua aplica��o poder� fazer altera��es nas tabelas no banco de acordo com o "convencional". Para n�o permitir isso voc� pode usar o valor "none".
spring.jpa.hibernate.ddl-auto=update
##Configura��o que mostra que o SQL que foi executado
spring.jpa.properties.hibernate.show_sql=true
## foi necess�rio apagar o  spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect pois a vers�o do sqldialect que ele t� usando � a Hibernate ORM core version 7.2.0.Final, pode apagar que o c�digo cuida automaticamente
